#!/usr/bin/python

from ldapy.commandline import Commandline
from ldapy.ldapy import Ldapy
from ldapy.commands import List, ChangeDN, PrintWorkingDN, Cat
import sys

import logging
logger = logging.getLogger ("ldapy")
handler = logging.StreamHandler()
handler.setFormatter (logging.Formatter("%(levelname)s:%(name)s: %(message)s"))
logger.addHandler (handler)
logger.setLevel (logging.DEBUG)

if __name__ == "__main__":
    ldapy = Ldapy ()

    commands = [List (ldapy), ChangeDN (ldapy), PrintWorkingDN (ldapy),\
                Cat (ldapy)]

    cli = Commandline (commands)
    cli.loop ()

