#!/usr/bin/python

# This file is part of ldapy.
#
# ldapy is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ldapy is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ldapy.  If not, see <http://www.gnu.org/licenses/>.

from ldapy.commandline import Commandline
from ldapy.ldapy import Ldapy
from ldapy.commands import List, ChangeDN, PrintWorkingDN, Cat
import sys

import logging
logger = logging.getLogger ("ldapy")
handler = logging.StreamHandler()
handler.setFormatter (logging.Formatter("%(levelname)s:%(name)s: %(message)s"))
logger.addHandler (handler)
logger.setLevel (logging.NOTSET)

if __name__ == "__main__":
    ldapy = Ldapy ()

    commands = [List (ldapy), ChangeDN (ldapy), PrintWorkingDN (ldapy),\
                Cat (ldapy)]

    cli = Commandline (commands)
    cli.loop ()

