#!/usr/bin/python

from commandline import Commandline
from ldapy import Ldapy
from commands import List, ChangeDN, PrintWorkingDN, Cat
import connection
import sys

import logging
logger = logging.getLogger ("ldapy")
handler = logging.StreamHandler()
handler.setFormatter (logging.Formatter("%(levelname)s:%(name)s: %(message)s"))
logger.addHandler (handler)
logger.setLevel (logging.DEBUG)

# Test data
uri = "ldap://localhost"
admin = "cn=admin,dc=nodomain"
admin_password = "foobar"

if __name__ == "__main__":
    ldapy = Ldapy ()

    commands = [List (ldapy), ChangeDN (ldapy), PrintWorkingDN (ldapy),\
                Cat (ldapy)]

    cli = Commandline (commands)
    cli.loop ()

